### ISSUE TITLE
模组导致游戏加载时间变长

### ISSUE THREAD

**Issue by Omgise** [tesseract4d/MysteriumLibUnofficial#1]
![image](https://github.com/tesseract4d/MysteriumLibUnofficial/assets/106000018/279fbe53-559d-4891-aed3-a9015b9ba511)

**Comment by Omgise** [comment]
正常来说一分多钟差不多就可以进入游戏界面了

**Comment by Omgise** [comment]
[fml-client-latest.log](https://github.com/tesseract4d/MysteriumLibUnofficial/files/15481423/fml-client-latest.log)
[latest.log](https://github.com/tesseract4d/MysteriumLibUnofficial/files/15481424/latest.log)

**Comment by huihiuhuai** [comment]
原版MysteriumLib也会延长加载时间

**Comment by Omgise** [comment]
还真是

**Comment by Omgise** [comment]
@tesseract4d 有可能修复这个问题吗（

**Comment by huihiuhuai** [comment]
是不是得去问问原作者

**Comment by huihiuhuai** [comment]
@Omgise 你用什么模组来显示加载时间

**Comment by huihiuhuai** [comment]
我问了原作者，作者也不知道是什么导致的

**Comment by tesseract4d** [comment]
这个还真没注意，我待会自己先测试一下

**Comment by tesseract4d** [comment]
修不好的话我换Mixin算了

**Comment by tesseract4d** [comment]
要不把你包发过来给我测试一下

**Comment by Omgise** [comment]
可以的，等我一下

**Comment by Omgise** [comment]
https://drive.google.com/file/d/1g7mTrLyt0WV0M-HmyJAmtb_65U64RrTj/view?usp=sharing

**Comment by tesseract4d** [comment]
非常坏MysteriumLib，使我的Minecraft启动时间翻倍

**Comment by tesseract4d** [comment]
奇怪的是Immersive Cavegen和Immersive Snowgen都内置了MysteriumLib，但并没有影响

**Comment by Omgise** [comment]
会不会是MysteriumLib自己的问题

**Comment by Omgise** [comment]
还有ADFix也内置了MysteriumLib

**Comment by Omgise** [comment]
ADFix：https://modrinth.com/mod/achievement-detection-fix

**Comment by tesseract4d** [comment]
不加MysteriumLib加这些内置了的模组一样可以作为前置正常运行
莫名其妙
我决定clone个内置了MysteriumLib模组过来把其他部分删了看看

**Comment by tesseract4d** [comment]
好像成功了，看了好几遍但就是不知道怎么做到的
被申必代码气笑了

**Comment by huihiuhuai** [comment]
> 会不会是MysteriumLibUnofficial自己的问题，我记得原版的MysteriumLib放进去游戏就直接崩溃了

所以你的崩溃会不会是因为mysterium lib重复了
