### ISSUE TITLE
1.5.8 cause bug with Et Futurum Requiem

### ISSUE THREAD

**Issue by huihiuhuai** [Tesseract4D/MysteriumLibUnofficial#2]
Can fly through walls in creative mode or with fly turn on even the player is not in spectator mode.

**Comment by huihiuhuai** [comment]
mods: unimixns, efr, myteriumlib

**Comment by Tesseract4D** [comment]
这真是特性

**Comment by huihiuhuai** [comment]
什么意思

**Comment by huihiuhuai** [comment]
这是你的模组增加的特性吗

**Comment by huihiuhuai** [comment]
能够默认禁用吗，不然不知道的人很可能以为是 bug
